name: Compile tinymesa

on:
  workflow_dispatch:
  schedule:
    - cron: '15 0 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'meson.build'
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Build ${{ matrix.tag }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, ubuntu-22.04-arm, macos-14 ]
        tag: [ mesa-25.2.7 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup tinymesa
        uses: ./.github/actions/setup
      - name: Clone mesa
        run: git clone --depth 1 --branch ${{ matrix.tag }} https://gitlab.freedesktop.org/mesa/mesa.git ${{ github.workspace }}/mesa
      - name: Patch mesa
        run: ./apply_patches.py ${{ github.workspace }}/mesa ${{ matrix.tag }}
      - name: Build mesa
        shell: bash
        run: |
          cd ${{ github.workspace }}/mesa
          export CLANG_PATH=$(which clang-20)
          meson setup build/ -Db_staticpic=true -Dgallium-drivers=llvmpipe -Dplatforms="[]" -Dglx=disabled -Dvulkan-drivers=swrast,nouveau,freedreno -Dopengl=false -Degl=disabled -Dgbm=disabled -Dvideo-codecs="[]"
          EXT=$([[ "${{ runner.os }}" == "macOS" ]] && echo ".dylib" || echo ".so")
          ninja -C build src/tinymesa/libtinymesa$EXT src/tinymesa/libtinymesa_cpu$EXT
      - name: Build wheel
        run: ./build_wheel.py ${{ matrix.tag }} 1337 ${{ github.workspace }}/mesa/src/tinymesa/libtinymesa${{ runner.os == 'macOS' && '.dylib' || '.so' }} ${{ github.workspace }}/mesa/src/tinymesa/libtinymesa_cpu${{ runner.os == 'macOS' && '.dylib' || '.so' }}
      - name: Test loading with ctypes
        run: |
          pip install dist/*.whl
          python3 -c "from ctypes import CDLL; from tinymesa import libtinymesa, libtinymesa_cpu; CDLL(libtinymesa).glsl_type_singleton_init_or_ref(), CDLL(libtinymesa_cpu).glsl_type_singleton_init_or_ref()"
      - name: Stage artifacts
        shell: bash
        run: |
          mkdir dist
          BUILD_DIR="${{ github.workspace }}/mesa/build/src/tinymesa"
          find $BUILD_DIR -maxdepth 1 -type f -print0 | xargs -0 -n1 basename | while read -r f; do
            mv "$BUILD_DIR/$f" "dist/${f/./-${{ matrix.tag }}-${{ format('{0}-{1}', runner.os == 'macOS' && matrix.os || 'linux', runner.arch == 'X64' && 'amd64' || 'arm64') }}.}"
          done
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tinymesa-whl-${{ matrix.tag }}-${{ matrix.os }}
          path: dist/
  release:
    name: Release tinymesa
    runs-on: ubuntu-22.04
    needs: build
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Create/update release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            TAG="${{ github.ref_name }}"
          else
            EXACT_TAG=$(git describe --tags --exact-match ${{ github.sha }} 2>/dev/null || echo "")
            if [[ -n "$EXACT_TAG" ]]; then
              exit 0
            fi
            TAG="tinymesa-${GITHUB_SHA::7}"
          fi

          if gh release view "$TAG"; then
            gh release upload "$TAG" artifacts/*/* --clobber=false
          else
            awk -f release.awk meson.build | gh release create "$TAG" artifacts/*/* --title "$TAG" -F -
          fi
