name: Rebuild all releases
on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '**.ld'

permissions:
  contents: write
  actions: write

jobs:
  rebuild:
    name: Delete all releases and rebuild
    runs-on: ubuntu-24.04
    steps:
      - name: Delete all releases
        shell: bash
        run: |
          TAGS=$(gh release list --limit 1000 --json tagName -q '.[].tagName')
          if [[ -z "$TAGS" ]]; then; echo "no releases to delete"
          else
            for TAG in $TAGS; do
              echo "DELETING: $TAG"
              gh release delete "$TAG" -y --cleanup-tag
            done
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger rebuild
        run: gh workflow run compile.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

